package com.demo.tests;

import com.demo.base.BaseTest;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.options.ColorScheme;
import org.testng.Assert;
import org.testng.annotations.Test;
import java.nio.file.Paths;

public class GoogleHomeTest extends BaseTest {

    @Test(priority = 1)
    public void testNavigationToDocs() {
        // Test 1: Standard navigation flow
        page.navigate("https://playwright.dev/java/");
        
        Locator getStartedBtn = page.locator("text=Get started");
        Assert.assertTrue(getStartedBtn.isVisible(), "Get Started button should be visible");
        
        getStartedBtn.click();
        Assert.assertTrue(page.url().contains("/docs/intro"), "URL did not transition to the intro docs page.");
    }

    @Test(priority = 2)
    public void testDarkModeEmulation() {
        // Test 2: FIX - Set emulation preference BEFORE navigating to the application
        page.emulateMedia(new Page.EmulateMediaOptions().setColorScheme(ColorScheme.DARK));
        page.navigate("https://playwright.dev/java/");
        
        Locator htmlTag = page.locator("html");
        String dataTheme = htmlTag.getAttribute("data-theme");
        
        Assert.assertEquals(dataTheme, "dark", "The website did not honor the dark mode browser emulation preference.");
        
        page.screenshot(new Page.ScreenshotOptions().setPath(Paths.get("target/surefire-reports/dark-mode-check.png")));
    }

    @Test(priority = 3)
    public void testSearchModalAndInput() {
        // Test 3: FIX - Reset theme context back to light/default state, navigate, and wait for action availability
        page.emulateMedia(new Page.EmulateMediaOptions().setColorScheme(ColorScheme.LIGHT));
        page.navigate("https://playwright.dev/java/");
        
        // Wait explicitly for the page container to load before clicking buttons
        Locator searchTrigger = page.locator(".DocSearch-Button");
        searchTrigger.waitFor();
        searchTrigger.click();
        
        // Target using the distinct classes generated by DocSearch
        Locator searchInput = page.locator(".DocSearch-Input");
        searchInput.waitFor(); // Safe wait for transition modal animation
        
        Assert.assertTrue(searchInput.isVisible(), "Search dialog input modal did not display.");
        searchInput.fill("Assertions");
        
        // Wait for results lists dropdown to populate before executing inner assertion
        page.waitForSelector(".DocSearch-Hit-title");
        Locator firstResult = page.locator(".DocSearch-Hit-title").first();
        
        Assert.assertTrue(firstResult.innerText().toLowerCase().contains("assertion"), 
                "Search drop-down suggestions did not surface relevant content queries.");
    }
}